use_frameworks!
platform :ios, '8.0'
target 'CDLabel_Example' do
  pod 'CDLabel', :path => '../'
  pod 'GDPerformanceView', '~> 1.3.1'
  target 'CDLabel_Tests' do
    inherit! :search_paths

    
  end
end
